name: Lines of Code
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  line_counter:
    runs-on: ubuntu-latest
    name: Initialise
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Count The Lines
        uses: shadowmoose/GHA-LoC-Badge@1.0.0
        id: badge
        with:
          debug: false
          badge: .github/cloc.svg
          ignore: "_build/*"
          patterns: quartic/*.ml
          
      - name: Print the output
        run: |
          echo "Scanned: ${{ steps.badge.outputs.counted_files }}";
          echo "Line Count: ${{ steps.badge.outputs.total_lines }}";

      - name: Commit Badge
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Lines of Code badge - ${{ steps.badge.outputs.total_lines }}
          push_options: '--force'
